from pydantic import BaseModel, Field


class StepMetrics(BaseModel):
    """Metrics for a single agent step.
    Each step corresponds to one LLM generate -> sandbox execute cycle.
    All fields are required for evaluation, empty strings are acceptable
    for steps where a field doesn't apply (e.g., no sandbox execution).
    """
    step: int = Field(..., description="1-indexed iteration number")
    input_tokens: int = Field(..., description="Tokens sent to the LLM for this step")
    output_tokens: int = Field(..., description="Tokens generated by the LLM for this step")
    request_time_ms: float = Field(..., description="Wall-clock time for the LLM API call in milliseconds")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO 8601 timestamp of when this step was recorded")
    api_url: str = Field(default="", description="Base URL of the LLM API endpoint (e.g., 'https://openrouter.ai/api/v1')")
